import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import BackgroundScreen from "@/app/components/BackgroundScreen";
import { ReduxProvider } from "@/app/ReduxProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col"
        style={{ backgroundColor: "white" }}
      >
        <ReduxProvider>
          <Header />
          <BackgroundScreen>{children}</BackgroundScreen>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
